name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
        sudo apt update -yqq
        DEBIAN_FRONTEND=noninteractive sudo apt install -y cmake clang-tidy build-essential pkg-config zip unzip tar

      # Set up vcpkg
      - name: Set up vcpkg
        run: |
          cd ..
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        # Cache vcpkg to speed up builds
        id: vcpkg

      # Build project
      - name: Build with CMake
        run: ./compile.sh

      # Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
          ./test/tests

      # Run clang-tidy
      - name: Lint code with clang-tidy
        run: |
          clang-tidy --version
          find src -name "*.cpp" | xargs -I {} clang-tidy {} -- -Iinclude
